import { client } from "@/api";
import { LayoutQuery, ProductQuery, ProductsListQuery } from "@/api/queries";
import { Product } from "@/mocks";
import { Metadata } from "next";
import { draftMode } from "next/headers";
import Link from "next/link";

type Props = {
  params: {
    slug: string;
  };
};

export const generateStaticParams = async () => {
  const { products } = await client.request<{ products: Product[] }>(
    ProductsListQuery,
  );
  return products.map(({ slug }) => ({ params: { slug } }));
};

export const generateMetadata = async ({
  params: { slug },
}: Props): Promise<Metadata> => {
  const { isEnabled } = draftMode();
  const { product } = await client.request<{ product: Product }>(ProductQuery, {
    slug,
    isEnabled,
  });

  return {
    title: product.slug,
    description: "Generated by create next app",
  };
};

export default async function Page({ params: { slug } }: Props) {
  const { isEnabled } = draftMode();
  const { product } = await client.request<{ product: Product }>(ProductQuery, {
    slug,
    isEnabled,
  });

  return (
    <>
      <h1>{product.slug}</h1>
      <nav className="flex flex-col">
        <Link href={`/`}>Home</Link>
        <Link href={`/products`}>Products</Link>
      </nav>
    </>
  );
}
