import { client } from "@/api";
import { LayoutQuery } from "@/api/queries";
import { Metadata } from "next";
import { draftMode } from "next/headers";
import Link from "next/link";

export const generateMetadata = async (): Promise<Metadata> => {
  const { isEnabled } = draftMode();
  await client.request(LayoutQuery, { isEnabled });

  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
};

export default async function Page() {
  const { isEnabled } = draftMode();
  await client.request(LayoutQuery, { isEnabled });

  return (
    <div>
      <Link href={`/products`}>Products</Link>
    </div>
  );
}
