import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { time } = await fetch("http://localhost:3000/api/layout", {
    headers: {
      "content-type": "application/json",
    },
    next: {
      revalidate: 5,
    },
  }).then((res) => res.json());

  return (
    <html lang="en">
      <body className={inter.className}>
        <time>{time}</time>
        {children}
      </body>
    </html>
  );
}
